### PR TITLE
feat(barcode-scanning): vote system

### PR DESCRIPTION
**Pull request by robingenz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).
- [ ] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

Related to #96

### CODE REVIEW

**Comment by corpro** [comment]
Tested works awesome!

**Comment by viharshitha** [comment]
@robingenz In which barcode version, this fix is included

**Comment by robingenz** [comment]
@viharshitha This is a feature and it's included in 6.2.0.

**Comment by viharshitha** [comment]
Thanks @robingenz  We got a Production issue, mis-reading a Z as a W (NCF85084Z4 was read as NCF85084W4). The scan was accepted and the incorrect serial number with W added. they had scan again. A subsequent scan was correct. 

**Does this problem solved by this PR?**

**Comment by robingenz** [comment]
@viharshitha   This PR definitely reduces the number of failed scans.

**Pull request merged**
