### PR TITLE
feat: add `@capacitor-mlkit/selfie-segmentation` package

### PR DESCRIPTION
**Pull request by robingenz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).

### CODE REVIEW

**Comment by trancee** [comment]
@robingenz I have just noticed when testing the implementation, that without the `enableRawSizeMask`, the app will crash because it has to return too many data points. If I enable the raw mask size, it returns 64KB of data points (256 x 256) which works.
But I wonder how this is helpful for segmenting the selfie picture. Looking at the samples from Google, they apply the segmentation mask to the input image and return the segmented picture. This might be more useful for this package, what do you think?

**Comment by robingenz** [comment]
@trancee Yes, you're right. Do you already have an idea how best to implement it?
My suggestion would be the following:

```ts
/**
 * @since 5.2.0
 */
export interface ProcessImageOptions {
  /**
   * The local path to the image file.
   *
   * @since 5.2.0
   */
  path: string;
}

/**
 * @since 5.2.0
 * @see https://developers.google.com/android/reference/com/google/mlkit/vision/segmentation/SegmentationMask
 */
export interface ProcessImageResult {
  /**
   * Returns a mask that indicates the foreground and background segmentation.
   *
   * @since 5.2.0
   */
  mask: number[];
  /**
   * Returns the width of the mask.
   *
   * @since 5.2.0
   */
  width: number;
  /**
   * Returns the height of the mask.
   *
   * @since 5.2.0
   */
  height: number;
  /**
   * The path to the generated foreground image file.
   * 
   * @since 5.2.0
   */
  foregroundImagePath: string;
  /**
   * The path to the generated background image file.
   * 
   * @since 5.2.0
   */
  backgroundImagePath: string;
}
```

`mask` would always be the `rawSizeMask` and the images could be saved in the `tmp` folder and the filenames could be `{filename}-foreground.{extension}` and `{filename}-background.{extension}`.

What do you think?

**Comment by trancee** [comment]
> `mask` would always be the `rawSizeMask` and the images could be saved in the `tmp` folder and the filenames could be `{filename}-foreground.{extension}` and `{filename}-background.{extension}`.
> 
> What do you think?

Yes, I think that's a good idea. I will try to implement it this way.

**Comment by robingenz** [comment]
@trancee Is this PR ready for merge?

**Comment by trancee** [comment]
> @trancee Is this PR ready for merge?

I will update the iOS implementation first, then it should be ready.

**Comment by robingenz** [comment]
@trancee Can we merge that as well?

**Comment by trancee** [comment]
> @trancee Can we merge that as well?

Yes, I am done with the implementation. Good to merge!

**Comment by robingenz** [comment]
@trancee Thank you again for your contributions! 😉

**Pull request merged**
