### PR TITLE
fix(barcode-scanning): resolve the `startScan(...)` method (#50)

### LINKED ISSUE #48: bug:
### Plugin(s)

- [X] Barcode Scanning
- [ ] Translation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

The `startScan()` method returns a Promise that is never resolved.

### Expected behavior

The Promise should resolve.

### Reproduction

https://github.com/JanMisker/capacitor-mlkit-plugin-demo

### Steps to reproduce

Run the demo app. 
I added a `console.log("before startScan()")` and `console.log("after startScan()")`. 
On Android I see both messages logged, but on iOS only the `before` one.

### Other information

_No response_

### Capacitor doctor

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.0
  @capacitor/core: 5.0.0
  @capacitor/android: 5.0.0
  @capacitor/ios: 5.0.0

[success] iOS looking great! 👌
[error] Missing <manifest package=""> attribute in app/src/main
```

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

### PR DESCRIPTION
**Pull request by JanMisker**
Add a missing completion() call on successful startScan()

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).

Close #48

### CODE REVIEW

**Comment by robingenz** [comment]
@JanMisker Great, thank you!

**Comment by JanMisker** [comment]
@robingenz thanks for quick follow-up, I must admit I didn't run the code 🫣

**Comment by robingenz** [comment]
@JanMisker Can you please create a changeset with the following text using `npm run changeset`?

```
fix(ios): resolve the `startScan(...)` method
```

I don't have write access to your fork.

**Comment by JanMisker** [comment]
@robingenz Done

**Pull request merged**
