### PR TITLE
feat: add `@capacitor-mlkit/face-detection` package

### LINKED ISSUE #5: feat: Face detection
**Is your feature request related to a problem? Please describe:**

The [ML Kit Face Detection API](https://developers.google.com/ml-kit/vision/face-detection) is not yet supported.

**Describe the solution you'd like:**

Add a Face Detection plugin.

**Describe alternatives you've considered:**

**Additional context:**

### PR DESCRIPTION
**Pull request by robingenz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).

Close #5

### CODE REVIEW

**Comment by robingenz** [comment]
@trancee I will refactor the code a bit. It would be great if you could support me with testing once I'm done. I'll let you know then.

**Comment by trancee** [comment]
> @trancee I will refactor the code a bit. It would be great if you could support me with testing once I'm done. I'll let you know then.

Yes, sure. I have also added the plugin to the capacitor-mlkit-demo-plugin repo for testing (created PR but currently with locally linked NPM package).

**Comment by robingenz** [comment]
Thank you! I will get it done this week and let you know.

**Comment by robingenz** [comment]
@trancee I just published a dev version for testing:
```
npm i @capacitor-mlkit/face-detection@5.0.3-dev.1a9ddd6.1689870691
```

Let me know if you encounter any issues.

**Comment by trancee** [comment]
> @trancee I just published a dev version for testing:
> 
> ```
> npm i @capacitor-mlkit/face-detection@5.0.3-dev.1a9ddd6.1689870691
> ```
> 
> Let me know if you encounter any issues.

I added the dev package to the demo and tested it, seems to be working!

**Comment by robingenz** [comment]
@trancee Awesome, thank you! I will take a look at the demo soon.

**Pull request merged**
